import { createI18n,useI18n } from 'vue-i18n';

const messages = {

    pt: {
        apps: {
            pdvName: 'Ponto de Venda',
            configName: 'Configurações',
            employeeName: 'Funcionário',
            purchase: 'Compra',
            stock: 'Gestão de Estoque',
            invoicing: 'Faturamento'
        },
        words: {
            department: 'Departamento',
            connected: 'conectado',
            installed: 'instalados',
            module: 'modulos',
            by: 'por',
            create: 'Criar',
            company: 'Empresa',
            start: 'Iniciar',
            close: 'Fechar',
            end: 'Terminar',
            enter: 'Entrar',
            one: 'Uma',
            open: 'Abrir',
            continue: 'Continuar',
            see: 'Ver',
            order: 'Encomenda',
            sale: 'Venda',
            new: 'Novo',
            report: 'Relatório',
            article: 'Artigo',
            operation: 'Operações',
            evaluation: 'Avaliação',
            list: 'Lista',
            entry: 'Entrada',
            output: 'Saída',
            price: 'Preço',
            action: 'Ação',
            section: 'Seção',
            number: 'Número',
            state: 'Estado',
            result: 'Resultado',
            client: 'Cliente',
            employee: 'Funcionário',
            total: 'Total',
            group: 'Grupo',
            filter: 'Filtrar',
            change: 'Trocar',
            cash: 'Dinheiro',
            quantity: 'Quantidade',
            requested: 'Solicitada',
            canceled: 'Canceladas',
            completed: 'Concluída',
            search: 'Pesquisar...',
            name: 'Nome',
            panel: 'Painel',
            movement: 'Movimento',
            subject: 'Assunto',
            date: 'Data',
            added: 'Adicionado',
            expenses: 'Gastos',
            print: 'Imprimir',
            cost: 'Custo',
            profit: 'Lucro',
            select: 'Selecionar',
            category: 'Categoria',
            provider: 'Fornecedor',
            notice: 'Informação',
            code: 'Código',
            barre: 'Código de Barras',
            save: 'Salvar',
            opened: 'Aberto',
            opening: 'Abertura',
            transfer: 'Transferência',
            card: 'Cartão',
            difference: 'Diferença',
            informed: 'Informado',
            payment: 'Pagamento',
            continue: 'Continuar',
            goOut: 'Sair',
            cancel: 'Cancelar',
            credit: 'Crédito',
            discount: 'Desconto',
            tax: 'Imposto',
            due: 'Vencimento',
            final: 'Final',
            annul: 'Anular',
            user: 'Usuário',
            after: 'Depois',
            before: 'Antes',
            admin: 'Administrador',
            paid: 'Pago',
            pay: 'Pagar',
            surname: 'Sobrenome',
            phone: 'Telefone',
            country: 'País',
            city: 'Cidade',
            road: 'Rua',
            delete: 'Eliminar',
            archive: 'Arquivar',
            purchase: 'Compra',
            merchandise: 'Mercadoria',
            department: 'Departamento',
            store: 'Armazém',
            responsible: 'Responsável',
            of: 'de',
            amount: 'montante',
            calendar: 'calendario',
            related: 'relacionado',
            last: 'ultima',
            inventory: 'inventário',
            validate: 'validar',
            missing: 'em falta',
            edit: 'editar',
            show: 'mostrar',
            box: 'caixa',
            or: 'ou',
            type: 'tipo',
            sessions: 'Sesão',
            manager: 'Gerente',
            neighborhood: 'Bairo',
            houseNumber: 'Numero de casa',
            activityType: "Tipo de atividades",
            currency: 'Moeda',
            localisation: 'Localisação da empresa',
            level: "Nivel de acesso",
            image: 'Imagem',
            security: 'Segurança',
            definition: 'Definições',
            update: 'Atualizar',
            gender: 'Genero',
            birthday: 'Aniversario',
            userConfig: {
                print: 'Imprimir informação completa no PDV',
                reprint: 'Reimprimir recibo PDV',
                stockMovement: 'Pode fazer entrada de stock',
                accesPrice: 'Acesso aos preços',
                languase: 'Idioma'
            },
            catalog: 'Catalogo',
            trainer: 'Trenadore',
            activity: 'Atividades',
            salary: 'Salario',
            title: 'Cargo',
            reportSalary:'Folha de salario',
            employeeObj:{
                times: 'Horario de trabalho',
                dialyExpen: 'Dispesas diarias',
                user: 'Usuario relacionado'
            },
            stockObj: {
                qtdRequested: 'Total de quantidade solicitada',
                qtdCanseled: 'otal de quantidade devolvidos',
                qtdConq: 'Total de quantidade comprados',
                prodMxProfit: 'Produto com mais lucro',
                prodMinProfit: 'Produto com menos lucro',
                prodMxSale: 'Produto mais vendido',
                prodMinSale: 'Produto menos vendido',
                storeDestination: 'Armagen de destino',
                dateTransfer: 'Data de transferencia',
                itemsSold: 'Produtos vendidos',
                qtdAvailable: 'Quantidades disponiveis',
                qtdSold: 'Quantidade vendida',
                hasDiscount: 'Este artigo não tem disconto',
                stockUnevailable: 'Estoque indisponível',
                stockAvailable: 'Estoque disponível',
                itemDiscount: 'Itens com desconto'
            },
        },
        pdv: {
            openingDate: 'Data de Abertura',
            closeDate: 'Data de Fechamento',
            openingBy: 'Aberto por',
            formedMoney: 'Valor enformado'
        },
        phrases: {
            typeProductName: 'Digite o nome do artigo',
            priceProduct: 'O preço do artigo',
            costPrice: 'Preço de compra',
            salePrice: 'Preço de venda',
            totalCost: 'Custo total',
            totalSale: 'Vendas totais',
            unitProfit: 'Lucro unitário',
            totalProfit: 'Lucro total',
            openingDate: 'Data de Abertura',
            closeDate: 'Data de Fechamento',
            openingBy: 'Aberto por',
            feature: 'Funcionalidade',
            userExperience: 'Experiência do usuário',
            securityUpdate: 'Atualização de segurança',
            opSessionContr: 'Abertura de controlo da seção',
            amountOpining: 'Valor de abertura',
            nifCompany: "Numero de identificação fiscal",
            companyName: "Nome da empresa",
            userInfo: 'Informações do usuário',
            confirmPassword: 'Confirme sua senha'

        },
        login: {
            title: 'Identifique-se',
            password: 'Senha',
            info: [
                {
                    title: 'Sistema de PDV Avançado',
                    description: 'Melhore a eficiência das suas vendas com o nosso Módulo de PDV de última geração.'
                },
                {
                    title: 'Emissão de Faturas e Controle Financeiro',
                    description: 'Simplifique a emissão de faturas e controle as finanças da sua empresa com o nosso Módulo de Faturamento.'
                },
                {
                    title: 'Gestão de Compras Simplificada',
                    description: 'Otimize o seu processo de compra com o nosso Módulo de Compras.'
                },
                {
                    title: 'Nova Funcionalidade',
                    description: 'Explore nossa última funcionalidade que aprimora a experiência do usuário.'
                },
                {
                    title: 'Atualização de Segurança',
                    description: 'Garanta a segurança de seus dados com nossa última atualização de sistema.'
                }
            ]
        }
    },

    fr: {
        apps: {
            pdvName: 'Point de Vente',
            configName: 'Définitions',
            employeeName: 'Employée',
            purchase: 'Achat',
            stock: 'Gestion de stock',
            invoicing: 'Facturation'
        },
        words: {
            department: 'Département',
            connected: 'connecté',
            installed: 'installée',
            module: 'module',
            by: 'par',
            create: 'Créer',
            company: 'Entreprise',
            start: 'Démarrer',
            close: 'Fermer',
            end: 'Fin',
            enter: 'Entrer',
            one: 'Un',
            open: 'Ouvrir',
            continue: 'Continuer',
            see: 'Voir',
            order: 'Commande',
            sale: 'Vente',
            new: 'Nouveau',
            report: 'Rapport',
            article: 'Article',
            operation: 'Opérations',
            evaluation: 'Évaluation',
            list: 'Liste',
            entry: 'Entrée',
            output: 'Sortie',
            price: 'Prix',
            action: 'Action',
            section: 'Section',
            number: 'Numéro',
            state: 'État',
            result: 'Résultat',
            client: 'Client',
            employee: 'Employé',
            total: 'Total',
            group: 'Groupe',
            filter: 'Filtrer',
            change: 'Changer',
            cash: 'Espèces',
            quantity: 'Quantité',
            requested: 'Demandée',
            canceled: 'Annulées',
            completed: 'Terminée',
            search: 'Rechercher...',
            name: 'Nom',
            panel: 'Panneau',
            movement: 'Mouvement',
            subject: 'Sujet',
            date: 'Date',
            added: 'Ajouté',
            expenses: 'Dépenses',
            print: 'Imprimer',
            cost: 'Coût',
            profit: 'Profit',
            select: 'Sélectionner',
            category: 'Catégorie',
            provider: 'Fournisseur',
            notice: 'Avis',
            code: 'Code',
            barre: 'Code-barres',
            save: 'Enregistrer',
            opened: 'Ouvert',
            opening: 'Ouverture',
            transfer: 'Transfert',
            card: 'Carte',
            difference: 'Différence',
            informed: 'Informé',
            payment: 'Paiement',
            continue: 'Continuer',
            goOut: 'Sortir',
            cancel: 'Annuler',
            credit: 'Crédit',
            discount: 'Remise',
            tax: 'Taxe',
            due: 'Échéance',
            final: 'Final',
            annul: 'Annuler',
            user: 'Utilisateur',
            after: 'Après',
            before: 'Avant',
            admin: 'Administrateur',
            paid: 'Payé',
            pay: 'Payer',
            surname: 'Nom de famille',
            phone: 'Téléphone',
            country: 'Pays',
            city: 'Ville',
            road: 'Rue',
            delete: 'Supprimer',
            archive: 'Archiver',
            purchase: 'Achat',
            merchandise: 'Marchandise',
            department: 'Département',
            store: 'Magasin',
            responsible: 'Responsable',
            of: 'de',
            update: 'Metre à jour',
            amount: 'quantia',
            calendar: 'Calendrier',
            related: 'en rapport',
            last: 'dernier',
            inventory: 'inventaire',
            validate: 'valider',
            missing: 'manquante',
            edit: 'modifier',
            show: 'montre',
            box: 'boîte',
            or: 'ou',
            type: 'type',
            sessions: 'Session',
            manager: 'Directeur',
            neighborhood: 'Quartier',
            houseNumber: 'Numéro de maison',
            activityType: "type d'activité",
            currency: 'Devise',
            localisation: 'Emplacement de la société',
            level: "niveau d'accès",
            image: 'Image',
            security: 'Sécurité',
            definition: 'Définitions',
            gender: 'Genre',
            birthday: 'Anniversaire',
            userConfig: {
                print: 'Imprimer des informations complètes sur le PDV',
                reprint: 'Réimprimer le reçu du PDV',
                stockMovement: 'Peut effectuer une entrée de stock',
                accesPrice: 'Accès aux prix',
                languase: 'Langue'
            },
            catalog: 'Catalogue',
            reportSalary:'Feuille de paiement',
            title: 'Poste',
            trainer: 'Entraîneur',
            activity: 'Activités',
            salary: 'Salaire',
            employeeObj:{
                times: 'Horaire de travail',
                dialyExpen: 'Dépenses quotidiennes',
                user: 'Utilisateur associé'
            },
            stockObj: {
                qtdRequested: 'Quantité totale demandée',
                qtdCanseled: 'Quantité totale annulée',
                qtdConq: 'Quantité totale achetée',
                prodMxProfit: 'Produit le plus rentable',
                prodMinProfit: 'Produit le moins rentable',
                prodMxSale: 'Produit le plus vendu',
                prodMinSale: 'Produit le moins vendu',
                storeDestination: 'Stockage de destination',
                dateTransfer: 'Date de transfert',
                itemsSold: 'Produits vendus',
                qtdAvailable: 'Quantités disponibles',
                qtdSold: 'Quantité vendue',
                hasDiscount: "Cet article n'est pas réduit",
                stockUnevailable: 'Stock non disponible',
                stockAvailable: 'Stock disponible',
                itemDiscount: 'Articles en promotion'
            }

        },
        pdv: {
            openingDate: 'Date d\'ouverture',
            closeDate: 'Date de fermeture',
            openingBy: 'Ouvert par',
            formedMoney: 'Valeur saisie'
        },
        phrases: {
            typeProductName: 'Saisissez le nom de l\'article',
            priceProduct: 'Le prix de l\'article',
            costPrice: 'Prix d\'achat',
            salePrice: 'Prix de vente',
            totalCost: 'Coût total',
            totalSale: 'Ventes totales',
            unitProfit: 'Profit unitaire',
            totalProfit: 'Profit total',
            openingDate: 'Date d\'ouverture',
            closeDate: 'Date de fermeture',
            openingBy: 'Ouvert par',
            feature: 'Fonctionnalité',
            userExperience: 'Expérience utilisateur',
            securityUpdate: 'Mise à jour de sécurité',
            opSessionContr: 'Ouverture de contrôle de la session',
            amountOpining: "Montant d'ouverture",
            nifCompany: "Numéro d'identification fiscale",
            companyName: "Nom de l'entreprise",
            userInfo: "Informations d'utilisateur",
            confirmPassword: 'Confirmer votre mot de passe',

        },
        login: {
            title: 'Identifiez-vous',
            password: 'Mot de passe',
            info: [
                {
                    title: 'Système de PDV Avancé',
                    description: 'Améliorez l\'efficacité de vos ventes avec notre module de PDV de pointe.'
                },
                {
                    title: 'Émission de Factures et Contrôle Financier',
                    description: 'Simplifiez l\'émission de factures et contrôlez les finances de votre entreprise avec notre module de facturation.'
                },
                {
                    title: 'Gestion Simplifiée des Achats',
                    description: 'Optimisez votre processus d\'achat avec notre module d\'achats.'
                },
                {
                    title: 'Nouvelle Fonctionnalité',
                    description: 'Explorez notre dernière fonctionnalité qui améliore l\'expérience utilisateur.'
                },
                {
                    title: 'Mise à Jour de Sécurité',
                    description: 'Assurez la sécurité de vos données avec notre dernière mise à jour système.'
                }
            ]
        }
    },


    en: {
        apps: {
            pdvName: 'Point of Sale',
            configName: 'Settings',
            employeeName: 'Employee',
            purchase: 'Purchase',
            stock: 'Stock Management',
            invoicing: 'Invoicing',
        },
        words: {
            department: 'Departmente',
            connected: 'connected',
            installed: 'installed',
            module: 'module',
            by: 'by',
            create: 'Create',
            company: 'Company',
            start: 'Start',
            close: 'Close',
            end: 'End',
            enter: 'Enter',
            one: 'One',
            open: 'Open',
            continue: 'Continue',
            see: 'See',
            order: 'Order',
            sale: 'Sale',
            new: 'New',
            report: 'Report',
            article: 'Article',
            operation: 'Operations',
            evaluation: 'Evaluation',
            list: 'List',
            entry: 'Entry',
            output: 'Output',
            price: 'Price',
            action: 'Action',
            section: 'Section',
            number: 'Number',
            state: 'State',
            result: 'Result',
            client: 'Client',
            employee: 'Employee',
            total: 'Total',
            group: 'Group',
            filter: 'Filter',
            change: 'Change',
            cash: 'Cash',
            quantity: 'Quantity',
            requested: 'Requested',
            canceled: 'Canceled',
            completed: 'Completed',
            search: 'Search...',
            name: 'Name',
            panel: 'Panel',
            movement: 'Movement',
            subject: 'Subject',
            date: 'Date',
            added: 'Added',
            expenses: 'Expenses',
            print: 'Print',
            cost: 'Cost',
            profit: 'Profit',
            select: 'Select',
            category: 'Category',
            provider: 'Provider',
            notice: 'Notice',
            code: 'Code',
            barre: 'Bar',
            save: 'Save',
            opened: 'Opened',
            opening: 'Opening',
            transfer: 'Transfer',
            card: 'Card',
            difference: 'Difference',
            informed: 'Informed',
            payment: 'Payment',
            continue: 'Continue',
            goOut: 'Go Out',
            cancel: 'Cancel',
            credit: 'Credit',
            discount: 'Discount',
            tax: 'Tax',
            due: 'Due',
            final: 'Final',
            annul: 'Annul',
            user: 'User',
            after: 'After',
            before: 'Before',
            admin: 'Admin',
            paid: 'Paid',
            pay: 'Pay',
            surname: 'Surname',
            phone: 'Phone',
            country: 'Country',
            city: 'City',
            road: 'Road',
            delete: 'Delete',
            archive: 'Archive',
            purchase: 'Purchase',
            merchandise: 'Merchandise',
            department: 'Department',
            store: 'Store',
            responsible: 'Responsible',
            box: 'Box',
            sessions: 'Sessions',
            definition: 'Definitions',
            reported: 'Reported',
            of: 'of',
            tape: 'Tape',
            type: 'type',
            the: 'The',
            theArticle: 'Article',
            or: 'or',
            a: 'A',
            A: 'A',
            update: 'Update',
            reason: 'Reason',
            typeOperation: 'Operation Type',
            amount: 'amount',
            calendar: 'calendar',
            related: 'related',
            last: 'last',
            inventory: 'inventory',
            validate: 'validate',
            missing: 'missing',
            edit: 'edit',
            show: 'show',
            manager: 'Manager',
            neighborhood: 'Neighborhood',
            houseNumber: 'House number',
            activityType: "Type of activity",
            currency: 'Currency',
            localisation: 'Company location ',
            level: "Access level",
            image: 'Image',
            security: 'Security',
            gender: 'Gender',
            birthday: 'Birthday',
            userConfig: {
                print: 'Print complete information at the Point of Sale',
                reprint: 'Reprint Point of Sale receipt',
                stockMovement: 'Can make stock entry',
                accesPrice: 'Access to prices',
                languase: 'Language'
            },
            catalog: 'Catalog',
            reportSalary:'Payment sheet',
            title: 'Title',
            trainer: 'Trainer',
            activity: 'Activities',
            salary: 'Salary',
            employeeObj:{
                times: 'Work Schedule',
                dialyExpen: 'Daily Expenses',
                user: 'Related User'
            },
            stockObj: {
                qtdRequested: 'Total quantity requested',
                qtdCanseled: 'Total quantity canceled',
                qtdConq: 'Total quantity purchased',
                prodMxProfit: 'Product with highest profit',
                prodMinProfit: 'Product with lowest profit',
                prodMxSale: 'Best-selling product',
                prodMinSale: 'Least-selling product',
                storeDestination: 'Destination Storage',
                dateTransfer: 'Transfer Date',
                itemsSold: 'Items Sold',
                qtdAvailable: 'Available Quantities',
                qtdSold: 'Quantity Sold',
                hasDiscount: 'This item is not discounted',
                stockUnevailable: 'Unavailable stock',
                stockAvailable: 'Available stock',
                itemDiscount: 'Discounted items'
            }
        },
        pdv: {
            openingDate: 'Opening date',
            closeDate: 'Closing date',
            openingBy: 'Opened by',
            formedMoney: 'formed cash'
        },
        phrases: {
            typeProductName: 'Enter the name of the article',
            priceProduct: 'The price of the article',
            costPrice: 'Purchase price',
            salePrice: 'Sale price',
            totalCost: 'Total purchase',
            totalSale: 'Total sales',
            unitProfit: 'Unit profit',
            totalProfit: 'Total profit',
            openingDate: 'Opening date',
            closeDate: 'Closing date',
            openingBy: 'Opened by',
            feature: 'Feature',
            userExperience: 'User experience',
            securityUpdate: 'Security update',
            opSessionContr: 'Session control opening',
            amountOpining: 'Opening amount',
            companyName: "Company name",
            nifCompany: 'Identification Number',
            userInfo: 'User informations',
            confirmPassword: 'Confirm your password'
        },
        login: {
            title: 'Identify Yourself',
            password: 'Password',
            info: [
                {
                    title: 'Advanced POS System',
                    description: 'Enhance the efficiency of your sales with our state-of-the-art POS Module.'
                },
                {
                    title: 'Invoice Issuance and Financial Control',
                    description: 'Simplify invoice issuance and control your company\'s finances with our Billing Module.'
                },
                {
                    title: 'Simplified Purchase Management',
                    description: 'Optimize your purchasing process with our Purchasing Module.'
                },
                {
                    title: 'New Feature',
                    description: 'Explore our latest feature that enhances user experience.'
                },
                {
                    title: 'Security Update',
                    description: 'Ensure the security of your data with our latest system update.'
                }
            ]
        }
    }
};
const locale = localStorage.getItem('locale');
const i18n = createI18n({
    legacy: false,
    locale: locale || 'en',
    messages,
});

export default i18n;
