import { useCookies } from '@vueuse/integrations/useCookies'
import { createI18n,useI18n } from 'vue-i18n';

const messages = {
  pt: {
    apps: {
        pdvName: 'Ponto de venda',
    },
    words: {
        create: 'Criar',
        company: 'Empresa',
        start: 'Iniciar',
        close: 'Fechar',
        end: 'Terminar',
        enter: 'Entrar',
        one: 'uma',
        open: 'Abrir',
        continue: 'Cantinuar',
        see: 'Ver',
        order: 'Encomenda',
        sale: 'Venda',
        report: 'Relatório',
        article: 'Artigo',
        operation: 'Operações',
        evaluation: 'Avaliação',
        list: 'Lista',
        sessions: 'Sessões',
        entry: 'Entrada',
        output: 'Saida',
        price: 'Preço',
        action: 'Ação',
        section: 'Seção',
        number: 'Numero',
        state: 'Estado',
        new: 'Novo',
        result: 'Resultado',
        client: 'Cliente',
        employee: 'Funcionário',
        total: 'Total',
        groupe: 'Agrupar',
        filter: 'Filtrar',
        change: 'Troco',
        cash:'Numerário',
        quantity: 'Quantidade',
        requested: 'Solicitada',
        canceled: 'Canceladas',
        completed: 'Concluida',
        search: 'Pesquisar',
        name: 'Nome',
        panel: 'Painel',
        movement: 'Muvemento',
        subject: 'Assunto',
        date: 'Data',
        added: 'Adicionar',
        expenses: 'Gastos',
        print: 'Imprimir',
        cost: 'Custo',
        profit: 'Lucro',
        select: 'Selecionar',
        category: 'Categoria',
        provider: 'Fornecedor',
        notice: 'Informação',
        code: 'Código',
        barre: 'Barra',
        save: 'Salvar',
        opened: 'Aberto',
        opening: 'Abertura',
        transfer: 'Transferencia',
        card: 'Multicaixa',
        difference: 'Diferencia',
        informed: 'Informado',
        payment:'Pagamento',
        continue: 'Continuar',
        goOut: 'Sair',
        cancel: 'Cancelar',
        credit: 'Credito',
        discount: 'Desconto',
        tax: 'Imposto',
        due: 'Vencimento',
        final:'Final',
        annul: 'Anular',
        user: 'Usuario',
        after: 'Depois',
        before: 'Ante',
        admin: 'Administrador',
        paid: 'Pago',
        pay: 'Pagar',
        surname: 'Apelido',
        phone: 'Telefone',
        country: 'Pais',
        city: 'Cidade',
        road: 'Rua',
        delete: 'Eliminar',
        archive: 'Arquivar',
        purchase:'Compra',
        merchandise: 'Mercadoria',
        department: 'Departamento',
        store: 'Armagen',
        responsible: 'Responsavel',
        box: 'Caixa',
        definition: 'Definições',
        reported: 'Enformado',
        of: 'de',
        tape: 'Digite',
        type: 'Tipo',
        the: 'o',
        theArticle: "artigo",
        or: 'ou',
        a: 'uma',
        A: 'um',
        update: 'atualizar',
        reason: 'Motivo',
        typeOperation: "Tipo de operação"
    },
    pdv: {
        openingDate: 'Data de Abertura',
        closeDate: 'Data de Fechamento',
        openingBy: 'Aberto por',
    },
    phrases: {
        typeProductName: 'Digite o nome do artigo',
        priceProduct: 'o preço do artigo',
        costPrice: 'Preço de compra',
        salePrice: 'Preço de venda',
        totalCost: 'Total de compra',
        totalSale: 'Total de venda',
        unitProfit: 'Lucro unitário',
        totalProfit: 'Total de lucro',
    },
    login:{
        title: 'Identifique-se',
        password: 'Senha',
        info: [
            {
                title: 'Sistema de PDV Avançado',
                description: 'Melhore a eficiência das suas vendas com o nosso Módulo de PDV de última geração.'
            },
            {
                title: 'Emissão de Faturas e Controle Financeiro',
                description: 'Simplifique a emissão de faturas e controle as finanças da sua empresa com o nosso Módulo de Faturamento.'
            },
            {
                title: 'Gestão de Compras Simplificada',
                description: 'Otimize o seu processo de compra com o nosso Módulo de Compras.'
            },
        ]
    },
  },
  fr: {
        apps: {
            pdvName: 'Point de vente',
        },
        words: {
            create: 'Créer',
            company: 'Entreprise',
            start: 'Démarrer',
            close: 'Fermer',
            end: 'Terminer',
            enter: 'Entrer',
            one: 'Une',
            new: 'Nouvelle',
            open: 'Ouvrir',
            continue: 'Continuer',
            see: 'Voir',
            order: 'Commande',
            sale: 'Vente',
            report: 'Rapport',
            article: 'Article',
            sessions: 'Séances',
            operation: 'Opérations',
            evaluation: 'Évaluation',
            list: 'Liste',
            entry: 'Entrée',
            output: 'Sortie',
            price: 'Prix',
            action: 'Action',
            section: 'Section',
            number: 'Numéro',
            state: 'État',
            result: 'Résultat',
            client: 'Client',
            employee: 'Employé',
            total: 'Total',
            groupe: 'Grouper',
            filter: 'Filtrer',
            change: 'Changer',
            cash: 'Espèces',
            quantity: 'Quantité',
            requested: 'Demandée',
            canceled: 'Annulées',
            completed: 'Terminée',
            search: 'Rechercher',
            name: 'Nom',
            panel: 'Panneau',
            movement: 'Mouvement',
            subject: 'Sujet',
            date: 'Date',
            added: 'Ajouter',
            expenses: 'Dépenses',
            print: 'Imprimer',
            cost: 'Coût',
            profit: 'Profit',
            select: 'Sélectionner',
            category: 'Catégorie',
            provider: 'Fournisseur',
            notice: 'Information',
            code: 'Code',
            barre: 'Barre',
            save: 'Enregistrer',
            opened: 'Ouvert',
            opening: 'Ouverture',
            transfer: 'Transfert',
            card: 'Carte',
            difference: 'Différence',
            informed: 'Informé',
            payment: 'Paiement',
            continue: 'Continuer',
            goOut: 'Sortir',
            cancel: 'Annuler',
            credit: 'Crédit',
            discount: 'Remise',
            tax: 'Impôt',
            due: 'Échéance',
            final: 'Final',
            annul: 'Annuler',
            user: 'Utilisateur',
            after: 'Après',
            before: 'Avant',
            admin: 'Administrateur',
            paid: 'Payé',
            pay: 'Payer',
            surname: 'Nom de famille',
            phone: 'Téléphone',
            country: 'Pays',
            city: 'Ville',
            road: 'Rue',
            delete: 'Supprimer',
            archive: 'Archiver',
            purchase: 'Achat',
            merchandise: 'Marchandise',
            department: 'Département',
            store: 'Entrepôt',
            responsible: 'Responsable',
            box: 'boîte',
            definition: 'Définition',
            reported: 'Rapportée',
            of: 'de',
            tape: 'Taper',
            type: 'Type',
            the: 'le',
            theArticle: "l'article",
            or: 'ou',
            a: 'une',
            A: 'un',
            update: 'mettre à jour',
            reason: 'Raison',
            typeOperation: "Type d'opération"
        },
        pdv: {
            openingDate: "Date d'ouverture",
            closeDate: 'Date de fermeture',
            openingBy: 'Ouvert par'
        },
        phrases: {
            typeProductName: "Entrez le nom de l'article",
            priceProduct: "le prix du l'article",
            costPrice: "Prix d'achat",
            salePrice: 'Prix de vente',
            totalCost: "Acha total",
            totalSale: 'Ventes totales',
            unitProfit: 'Bénéfice unitaire',
            totalProfit: 'Total de bénéfice',
        },
        login: {
            title: 'Identifiez-vous',
            password: 'Mot de passe',
            info: [
                {
                    title: 'Système de PDV Avancé',
                    description: "Améliorez l'efficacité de vos ventes avec notre module PDV de dernière génération."
                },
                {
                    title: 'Émission de factures et contrôle financier',
                    description: "Simplifiez l'émission de factures et contrôlez les finances de votre entreprise avec notre module de facturation."
                },
                {
                    title: 'Gestion simplifiée des achats',
                    description: "Optimisez votre processus d'achat avec notre module d'achats."
                },
            ]
        },
    },
    en: {
        apps: {
            pdvName: 'Point of Sale',
        },
        words: {
            create: 'Create',
            company: 'Company',
            start: 'Start',
            close: 'Close',
            end: 'End',
            enter: 'Enter',
            one: 'One',
            open: 'Open',
            continue: 'Continue',
            see: 'See',
            order: 'Order',
            sale: 'Sale',
            new: 'New',
            report: 'Report',
            article: 'Article',
            operation: 'Operations',
            evaluation: 'Evaluation',
            list: 'List',
            entry: 'Entry',
            output: 'Output',
            price: 'Price',
            action: 'Action',
            section: 'Section',
            number: 'Number',
            state: 'State',
            result: 'Result',
            client: 'Client',
            employee: 'Employee',
            total: 'Total',
            group: 'Group',
            filter: 'Filter',
            change: 'Change',
            cash: 'Cash',
            quantity: 'Quantity',
            requested: 'Requested',
            canceled: 'Canceled',
            completed: 'Completed',
            search: 'Search',
            name: 'Name',
            panel: 'Panel',
            movement: 'Movement',
            subject: 'Subject',
            date: 'Date',
            added: 'Added',
            expenses: 'Expenses',
            print: 'Print',
            cost: 'Cost',
            profit: 'Profit',
            select: 'Select',
            category: 'Category',
            provider: 'Provider',
            notice: 'Notice',
            code: 'Code',
            barre: 'Bar',
            save: 'Save',
            opened: 'Opened',
            opening: 'Opening',
            transfer: 'Transfer',
            card: 'Card',
            difference: 'Difference',
            informed: 'Informed',
            payment: 'Payment',
            continue: 'Continue',
            goOut: 'Go Out',
            cancel: 'Cancel',
            credit: 'Credit',
            discount: 'Discount',
            tax: 'Tax',
            due: 'Due',
            final: 'Final',
            annul: 'Annul',
            user: 'User',
            after: 'After',
            before: 'Before',
            admin: 'Admin',
            paid: 'Paid',
            pay: 'Pay',
            surname: 'Surname',
            phone: 'Phone',
            country: 'Country',
            city: 'City',
            road: 'Road',
            delete: 'Delete',
            archive: 'Archive',
            purchase: 'Purchase',
            merchandise: 'Merchandise',
            department: 'Department',
            store: 'Store',
            responsible: 'Responsible',
            box: 'Box',
            sessions: 'Sessions',
            definition: 'Definitions',
            reported: 'Reported',
            of: 'of',
            tape: 'Type',
            type: 'Type',
            the: 'the',
            theArticle: "article",
            or: 'or',
            a: 'a',
            A: 'a',
            update: 'to update',
            reason: 'Reason',
            typeOperation: "Operation type"
        },
        pdv:{
            openingDate: 'Opening date',
            closeDate: 'Closing date',
            openingBy: 'opened by'
        },
        phrases: {
            typeProductName: 'Enter the name of the article',
            priceProduct: 'the price of the article',
            costPrice: 'Purchase price',
            salePrice: 'Sale price',
            totalCost: "Total purchase",
            totalSale: 'Total sales',
            unitProfit: 'Unit profit',
            totalProfit: 'Total profit',
        },
        login: {
            title: 'Identify Yourself',
            password: 'Password',
            info: [
                {
                    title: 'Advanced POS System',
                    description: 'Enhance the efficiency of your sales with our state-of-the-art POS Module.'
                },
                {
                    title: 'Invoice Issuance and Financial Control',
                    description: "Simplify invoice issuance and control your company's finances with our Billing Module."
                },
                {
                    title: 'Simplified Purchase Management',
                    description: 'Optimize your purchasing process with our Purchasing Module.'
                },
            ]
        },
    }    
};
const cookie = useCookies(['locale'])
const i18n = createI18n({
    legacy: false,
    locale: cookie.get('locale') || 'en',
    messages,
});

export default i18n;
